import type { RunReport, TestResultSummary } from "@mcp-workbench/plugin-sdk";

export function generateHtml(report: RunReport, specFile?: string): string {
  const date = new Date().toLocaleString();
  const title = specFile ? `MCP Workbench — ${specFile}` : "MCP Workbench Report";
  const allPassed = report.failed === 0 && report.errors === 0;
  const statusBadge = allPassed
    ? `<span class="badge pass">PASS</span>`
    : `<span class="badge fail">FAIL</span>`;

  const testRows = report.tests.map(renderTest).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escHtml(title)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 0; background: #f5f7fa; color: #1a1d23; }
    header { background: #1a1d23; color: #fff; padding: 20px 32px; }
    header h1 { margin: 0; font-size: 18px; font-weight: 600; }
    header p { margin: 4px 0 0; font-size: 13px; opacity: 0.6; }
    .summary { display: flex; gap: 16px; padding: 20px 32px; background: #fff; border-bottom: 1px solid #e5e8ed; align-items: center; flex-wrap: wrap; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 4px; font-size: 13px; font-weight: 700; letter-spacing: 0.05em; }
    .badge.pass { background: #d1fae5; color: #065f46; }
    .badge.fail { background: #fee2e2; color: #991b1b; }
    .stat { font-size: 13px; color: #6b7280; }
    .stat strong { color: #1a1d23; }
    .stat.green strong { color: #059669; }
    .stat.red strong { color: #dc2626; }
    .stat.yellow strong { color: #d97706; }
    .duration { margin-left: auto; font-size: 12px; color: #9ca3af; }
    main { padding: 24px 32px; }
    .test { background: #fff; border: 1px solid #e5e8ed; border-radius: 8px; margin-bottom: 10px; overflow: hidden; }
    .test-header { display: flex; align-items: center; gap: 10px; padding: 12px 16px; cursor: pointer; }
    .test-header:hover { background: #f9fafb; }
    .icon { font-size: 14px; flex-shrink: 0; }
    .icon.pass { color: #059669; }
    .icon.fail { color: #dc2626; }
    .icon.error { color: #dc2626; }
    .icon.skip { color: #d97706; }
    .test-id { font-size: 13px; font-weight: 600; color: #1a1d23; }
    .test-desc { font-size: 12px; color: #6b7280; margin-left: 4px; }
    .test-ms { margin-left: auto; font-size: 11px; color: #9ca3af; }
    .assertions { padding: 0 16px 12px 40px; display: none; }
    .assertions.open { display: block; }
    .assertion { font-size: 12px; padding: 4px 0; border-top: 1px solid #f3f4f6; display: flex; align-items: flex-start; gap: 6px; }
    .assertion:first-child { border-top: none; }
    .a-icon.pass { color: #059669; }
    .a-icon.fail { color: #dc2626; }
    .a-kind { color: #6b7280; font-family: monospace; }
    .a-msg { color: #dc2626; }
    .a-diff { background: #f9fafb; border: 1px solid #e5e8ed; border-radius: 4px; padding: 8px; font-family: monospace; font-size: 11px; white-space: pre; overflow-x: auto; margin-top: 4px; color: #374151; }
    .error-msg { font-size: 12px; color: #dc2626; padding: 4px 0 4px 40px; }
    footer { text-align: center; padding: 24px; font-size: 12px; color: #9ca3af; }
  </style>
</head>
<body>
  <header>
    <h1>MCP Workbench Test Report</h1>
    <p>${escHtml(specFile ?? "")} &nbsp;·&nbsp; Generated ${escHtml(date)}</p>
  </header>

  <div class="summary">
    ${statusBadge}
    <span class="stat green"><strong>${report.passed}</strong> passed</span>
    ${report.failed > 0 ? `<span class="stat red"><strong>${report.failed}</strong> failed</span>` : ""}
    ${report.errors > 0 ? `<span class="stat red"><strong>${report.errors}</strong> errors</span>` : ""}
    ${report.skipped > 0 ? `<span class="stat yellow"><strong>${report.skipped}</strong> skipped</span>` : ""}
    <span class="stat"><strong>${report.total}</strong> total</span>
    <span class="duration">${report.durationMs}ms</span>
  </div>

  <main>
    ${testRows}
  </main>

  <footer>Generated by <strong>MCP Workbench</strong> · plugin-html-report</footer>

  <script>
    document.querySelectorAll('.test-header').forEach(function(el) {
      el.addEventListener('click', function() {
        var assertions = el.nextElementSibling;
        if (assertions) assertions.classList.toggle('open');
      });
    });
  </script>
</body>
</html>`;
}

function renderTest(t: TestResultSummary): string {
  const iconClass = t.status === "passed" ? "pass" : t.status === "skipped" ? "skip" : t.status === "error" ? "error" : "fail";
  const iconChar = t.status === "passed" ? "✓" : t.status === "skipped" ? "○" : "✗";
  const desc = t.description ? `<span class="test-desc">— ${escHtml(t.description)}</span>` : "";

  const assertionHtml = t.assertionResults.map((a) => {
    const ac = a.passed ? "pass" : "fail";
    const label = a.assertion.label ?? a.assertion.kind;
    const msgHtml = !a.passed && a.message
      ? `<span class="a-msg">${escHtml(a.message)}</span>`
      : "";
    const diffHtml = a.diff
      ? `<pre class="a-diff">${escHtml(a.diff)}</pre>`
      : "";
    return `<div class="assertion">
      <span class="a-icon ${ac}">${a.passed ? "✓" : "✗"}</span>
      <span>
        <span class="a-kind">${escHtml(label)}</span>
        ${msgHtml}
        ${diffHtml}
      </span>
    </div>`;
  }).join("\n");

  const errorHtml = t.error
    ? `<div class="error-msg">${escHtml(t.error)}</div>`
    : "";

  return `<div class="test">
  <div class="test-header">
    <span class="icon ${iconClass}">${iconChar}</span>
    <span class="test-id">${escHtml(t.testId)}</span>
    ${desc}
    <span class="test-ms">${t.durationMs}ms</span>
  </div>
  ${errorHtml}
  <div class="assertions">
    ${assertionHtml}
  </div>
</div>`;
}

function escHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
