import { Session } from "@mcp-workbench/session-engine";
import { StdioTransport } from "@mcp-workbench/transport-stdio";
import { HttpTransport } from "@mcp-workbench/transport-http";
import type { Transport } from "@mcp-workbench/protocol-kernel";
import { stringify } from "yaml";
import { inferArgs, type JsonSchema } from "./inference.js";
import type { GenerateOptions, GenerateResult } from "./types.js";

interface Tool {
  name: string;
  description?: string;
  inputSchema?: JsonSchema;
}

interface Resource {
  uri: string;
  name?: string;
  description?: string;
}

interface Prompt {
  name: string;
  description?: string;
  arguments?: Array<{ name: string; description?: string; required?: boolean }>;
}

/**
 * Connect to an MCP server, discover capabilities, and generate a YAML test spec.
 */
export async function generate(opts: GenerateOptions): Promise<GenerateResult> {
  const transport = buildTransport(opts);
  if (transport instanceof StdioTransport || transport instanceof HttpTransport) {
    await transport.connect();
  }

  const session = new Session(transport, {
    clientInfo: { name: "mcp-workbench-generate", version: "0.1.0" },
    requestTimeoutMs: opts.timeoutMs ?? 10_000,
  });

  try {
    const negotiated = await session.connect();
    const serverInfo = {
      name: negotiated.serverInfo.name,
      version: negotiated.serverInfo.version,
      protocol: negotiated.protocolVersion,
    };

    const caps = negotiated.serverCapabilities;
    const shouldInclude = (cap: "tools" | "resources" | "prompts"): boolean => {
      if (opts.exclude?.has(cap)) return false;
      if (opts.include && !opts.include.has(cap)) return false;
      return true;
    };

    // Discovery
    let tools: Tool[] = [];
    let resources: Resource[] = [];
    let prompts: Prompt[] = [];

    if (caps.tools && shouldInclude("tools")) {
      const result = await session.listTools();
      tools = result.tools as Tool[];
    }

    if (caps.resources && shouldInclude("resources")) {
      const result = await session.listResources();
      resources = result.resources as Resource[];
    }

    if (caps.prompts && shouldInclude("prompts")) {
      const result = await session.listPrompts();
      prompts = result.prompts as Prompt[];
    }

    // Build tests
    const tests = buildTests(tools, resources, prompts);

    // Build spec object
    const spec: Record<string, unknown> = {
      apiVersion: "mcp-workbench.dev/v0alpha1",
      server: buildServerBlock(opts),
      tests,
    };

    // Generate YAML
    const header = [
      `# Generated by: mcp-workbench generate`,
      `# Server: ${serverInfo.name} v${serverInfo.version} (protocol ${serverInfo.protocol})`,
      `# Review and customize before using in CI.`,
      ``,
    ].join("\n");

    const yaml = header + stringify(spec, { lineWidth: 0 });

    return {
      yaml,
      serverInfo,
      counts: {
        tools: tools.length,
        resources: resources.length,
        prompts: prompts.length,
        tests: tests.length,
      },
    };
  } finally {
    await session.close();
  }
}

function buildServerBlock(opts: GenerateOptions): Record<string, unknown> {
  if (opts.transport === "stdio") {
    const block: Record<string, unknown> = {
      transport: "stdio",
      command: opts.command,
    };
    if (opts.args) block.args = opts.args.split(/\s+/);
    return block;
  }

  const block: Record<string, unknown> = {
    transport: "streamable-http",
    url: opts.url,
  };
  if (opts.headers && Object.keys(opts.headers).length > 0) {
    block.headers = { ...opts.headers };
  }
  return block;
}

function buildTests(tools: Tool[], resources: Resource[], prompts: Prompt[]): unknown[] {
  const tests: unknown[] = [];

  // Tools
  if (tools.length > 0) {
    tests.push({
      id: "tools-list",
      description: "Server exposes tools",
      act: { method: "tools/list" },
      assert: [
        { kind: "status", equals: "success" },
        { kind: "notEmpty", path: "$.tools" },
      ],
    });

    for (const tool of tools) {
      const test: Record<string, unknown> = {
        id: `tool-${sanitizeId(tool.name)}`,
        description: `Tool: ${tool.name}`,
        act: {
          method: "tools/call",
          tool: tool.name,
        },
        assert: [
          { kind: "status", equals: "success" },
          { kind: "executionError", equals: false },
        ],
      };

      const args = inferArgs(tool.inputSchema as JsonSchema);
      if (args) {
        (test.act as Record<string, unknown>).args = args;
      }

      tests.push(test);
    }
  }

  // Resources
  if (resources.length > 0) {
    tests.push({
      id: "resources-list",
      description: "Server exposes resources",
      act: { method: "resources/list" },
      assert: [
        { kind: "status", equals: "success" },
        { kind: "notEmpty", path: "$.resources" },
      ],
    });

    for (const resource of resources) {
      tests.push({
        id: `resource-${sanitizeId(resource.name ?? resource.uri)}`,
        description: `Resource: ${resource.name ?? resource.uri}`,
        act: {
          method: "resources/read",
          uri: resource.uri,
        },
        assert: [{ kind: "status", equals: "success" }],
      });
    }
  }

  // Prompts
  if (prompts.length > 0) {
    tests.push({
      id: "prompts-list",
      description: "Server exposes prompts",
      act: { method: "prompts/list" },
      assert: [{ kind: "status", equals: "success" }],
    });

    for (const prompt of prompts) {
      const test: Record<string, unknown> = {
        id: `prompt-${sanitizeId(prompt.name)}`,
        description: `Prompt: ${prompt.name}`,
        act: {
          method: "prompts/get",
          name: prompt.name,
        },
        assert: [{ kind: "status", equals: "success" }],
      };

      const promptArgs = prompt.arguments;
      if (promptArgs && promptArgs.length > 0) {
        const args: Record<string, string> = {};
        for (const arg of promptArgs) {
          args[arg.name] = "TODO";
        }
        (test.act as Record<string, unknown>).args = args;
      }

      tests.push(test);
    }
  }

  return tests;
}

function sanitizeId(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function buildTransport(opts: GenerateOptions): Transport {
  if (opts.transport === "stdio") {
    if (!opts.command) throw new Error("--command is required for stdio transport");
    return new StdioTransport({
      command: opts.command,
      args: opts.args?.split(/\s+/) ?? [],
      inheritEnv: true,
    });
  }

  if (!opts.url) throw new Error("--url is required for streamable-http transport");
  return new HttpTransport({
    url: opts.url,
    headers: opts.headers,
    timeoutMs: opts.timeoutMs ?? 10_000,
  });
}
